### ISSUE TITLE
Create a Navbar

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#1]
A simple navbar would be sufficient, although you can go wild with your imagination and create something out of the box.

**Comment by aakshitaa** [comment]
sure

**Comment by helloakash1701** [comment]
Hey @aakshitaa , I have made a pr for this issue, can you please check it

**Comment by helloakash1701** [comment]
Hey @aakshitaa can you please check my pr

**Comment by helloakash1701** [comment]
Hey @aakshitaa how about now?

**Comment by anubhabdhar** [comment]
Can I take this up?

**Comment by aakshitaa** [comment]
yes you can @anubhabdhar, actually this is almost complete by @helloakash1701 but since there are changes required you can still work on this.

**Comment by aakshitaa** [comment]
@anubhabdhar kindly text hello on discord workspace so that I can share the UI there

**Comment by anubhabdhar** [comment]
@aakshitaa I am not aware of the discord workspace. Can you please share..

**Comment by aakshitaa** [comment]
https://discord.gg/92Dn8HYW 
Have you joined this?

**Comment by anubhabdhar** [comment]
> https://discord.gg/92Dn8HYW Have you joined this?

Yes I joined.

**Comment by helloakash1701** [comment]
Please check @aakshitaa

**Comment by aakshitaa** [comment]
This issue was completed by @helloakash1701 , therefore @anubhabdhar please find another issue to work on. All the best ✨
