### ISSUE TITLE
Details Page for user who wants to claim an item

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#10]
If a user finds their repective item from the items gallery page, then they will proceed to this page after clicking on claim now. This page will basically be a form and will contain user details including:
Name, SAP ID, Branch, Year, Contact Number, Date

**Comment by Kruthardh11** [comment]
I would like to take this up under OSoc 2023

**Comment by aakshitaa** [comment]
Okay Sure @Kruthardh11

**Comment by aakshitaa** [comment]
This issue has been completed by @Kruthardh11
