### ISSUE TITLE
Spacing between the items gallery and the footer

### ISSUE THREAD

**Issue by helloakash1701** [upes-open/OSoC-Lost-And-Found-WebApp#104]
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/80618499/8628b914-c2fe-4f3c-b1f8-94a0a9061a06)

**Comment by helloakash1701** [comment]
Can I work on this?

**Comment by aakshitaa** [comment]
okay sure @helloakash1701

**Comment by aakshitaa** [comment]
This issue was completed by @helloakash1701
