### ISSUE TITLE
Confirmation and Claiming Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#11]
This page will open after the user details page (once the user has entered all the relevant details) and this page will show that the user can successfully claim the item from Lost And Found Department

**Comment by helloakash1701** [comment]
I would like to work on this

**Comment by sachinaggarwal18** [comment]
I would like to work on this..

**Comment by aakshitaa** [comment]
okay cool @sachinaggarwal18

**Comment by aakshitaa** [comment]
@helloakash1701 this issue was completed by @sachinaggarwal18
