### ISSUE TITLE
Add the confirmation page after successfully adding user details in claiming procedure

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#113]
The confirmation page is created and is present in ./src/confirmation. Add it such that once the user fills its details after clicking the "claim item button" then this page will be displayed.

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
sure @ThapaVinay

**Comment by aakshitaa** [comment]
This issue was  completed by @ThapaVinay
