### ISSUE TITLE
Footer links not working

### ISSUE THREAD

**Issue by helloakash1701** [upes-open/OSoC-Lost-And-Found-WebApp#118]
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/80618499/f7136990-c324-4111-9bc6-763694866f2b)
Links like contact, visit us and emails not working

**Comment by helloakash1701** [comment]
Can you please assign me to this issue

**Comment by aakshitaa** [comment]
This issue was completed by @helloakash1701
