### ISSUE TITLE
Item Gallery Page- Display Items 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#12]
Once user has selected which category they want to see, fetch the data from Found Items DB and filter it out according to the selected category. Display the filtered data image wise. Once user clicks on the image, open it and display the details of that item. Show the "Claim Now" button there as well

**Comment by avoxaya** [comment]
Please assign this to me under OSoC'23.

**Comment by aakshitaa** [comment]
Sure @avoxaya , since  this is an advanced issue I believe you might need some help understanding the concept, so please feel free to text on the discord channel for this project and I'll be there to assist you.

**Comment by aakshitaa** [comment]
@avoxaya This issue has been modified. Instead of making the whole items gallery page with integrated backend at once, it has now been distributed in two issues. This one will comprise of the frontend- Making the UI of the page by using sample images 
And another issue will be made for integrating the backend and applying the logic to fetch the items from the found items DB and show the items based on category. 
Thus this issue is now intermediate. 

You can go ahead and get assigned the issue for backend integration as well and claim more points than you would have previously!

Happy Contributing  ✨

**Comment by aakshitaa** [comment]
**Note**

The issue for integrating items gallery page with backend will only be  made once  this issue is completed!

**Comment by aakshitaa** [comment]
@avoxaya This issue has been completed by @ThapaVinay
