### ISSUE TITLE
Add dark and light theme switch

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#13]
Add a theme switch option in the navbar which switches the theme of the entire WebApp from light to dark

**Comment by H-SM** [comment]
Can I take up the issue?

**Comment by tarunvenkat** [comment]
Hello @aakshitaa  I want to work on this issue please

**Comment by aakshitaa** [comment]
sure @tarunvenkat and @H-SM

**Comment by anubhabdhar** [comment]
Can I take this up?

**Comment by aakshitaa** [comment]
Yes you can

**Comment by shreyas2711** [comment]
Can I work on this?

**Comment by aakshitaa** [comment]
Yes you can @shreyas2711
