### ISSUE TITLE
User Profile Page- Main page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#133]
Create a profile page for the user which will be simple and will contain the name and email of the user as well as the signout button.
Make sure that you make the profile page suitable for both light and dark mode.

**Comment by ThapaVinay** [comment]
I want to work on this

**Comment by aakshitaa** [comment]
Sure @ThapaVinay

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
