### ISSUE TITLE
User Profile Page- Add icon on navbar

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#134]
Add an icon for the profile page  on the navbar. The icon can be something like:
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/a85b2a20-8e84-4d2d-9844-a1a2c71fc32c)
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/62986acc-b4c1-40f8-9e80-308f5a887826)
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/7dc6d18a-56dc-4149-924a-8f020298ae88)
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/efae342c-2e4d-478a-b4c8-b459fef1f11d)

# note - the button should only be visible once the user is logged in

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure @ThapaVinay, just remember that this icon will only be visible if the user is logged in

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
