### ISSUE TITLE
Add back to top button

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#14]
Add a button which on-click takes us back to top of the page. This button is for the Items Galley Page only

**Comment by helloakash1701** [comment]
I would like to work upon this issue

**Comment by ThapaVinay** [comment]
can i work on this?

**Comment by aakshitaa** [comment]
Yeah sure @ThapaVinay

**Comment by aakshitaa** [comment]
@helloakash1701 This issue was completed by @ThapaVinay . Please continue working on other issues. All the best !

**Comment by helloakash1701** [comment]
Sure🙌
