### ISSUE TITLE
Improve the readme.md

### ISSUE THREAD

**Issue by karthiknadar1204** [upes-open/OSoC-Lost-And-Found-WebApp#18]
Here i propose to make the readme elaborate by adding an elaborate way to open a pr and set up the project as well as shell commands so that anyone starting out with the project can start out easily

**Comment by aakshitaa** [comment]
Hello there
Updating the README.md is not a feature solving in the project.

the readme is already designed by our heads, also the documentation will be done at the last of the OSoC'23.

Updating the README.md will contain the UI screenshots, brief features of project.
