### ISSUE TITLE
Create a Feedback Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#19]
A feedback page where users can provide their feedback and grievances.

**Comment by priii-25** [comment]
Hey, Can I work on this?

**Comment by aakshitaa** [comment]
sure you can @priii-25

**Comment by ThapaVinay** [comment]
i want to work on this.

**Comment by aakshitaa** [comment]
Okay go ahead

**Comment by aakshitaa** [comment]
@priii-25  this issue has been completed by @ThapaVinay , you can get yourself assigned other issues if you want.
