### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#2]
A login page with the pre-determined design. Contributor can feel free to add their creativity to it, but make sure the basic design is not altered much.

**Comment by helloakash1701** [comment]
I would like to work on this

**Comment by Siddharthaaa21** [comment]
I would like to work on this if possible.

**Comment by aakshitaa** [comment]
sure @Siddharthaaa21

**Comment by jason2000-cpu** [comment]
I woul like to work on this under Osoc' 23

**Comment by aakshitaa** [comment]
Sure go ahead @jason2000-cpu

**Comment by aakshitaa** [comment]
@helloakash1701  @Siddharthaaa21 This issue was completed by @jason2000-cpu , Kindly find other issues to work on!
