### ISSUE TITLE
Design a Logo for our WebApp

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#21]
I believe every webapp should have a beautiful and attractive logo. So design one and we will integrate it in everywhere possible. Try to be creative, it'll be tought to be able to give desirable results for this one.

**Comment by divyansh2375** [comment]
i am ready to work on it .

**Comment by helloakash1701** [comment]
would like to work on this issue

**Comment by aakshitaa** [comment]
Yes sure @helloakash1701

**Comment by helloakash1701** [comment]
is it okay?

**Comment by aakshitaa** [comment]
This issue was completed by @helloakash1701
