### ISSUE TITLE
Create Help Us Find Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#24]
This Page will fetch data from Lost Items DB and show the users what all items are currently lost. Each item should have a button called 'REPORT AS FOUND' which will direct the user to the report found item page. Since images are not mandatory for the Lost Items DB hence this page may contain simple text as well as images, so design a UI Accordingly .See Workflow.md for more details.

**Comment by ThapaVinay** [comment]
can i work on this?

**Comment by aakshitaa** [comment]
Sure you can

**Comment by shreyas2711** [comment]
Can I work on this?

**Comment by aakshitaa** [comment]
Yes go ahead @shreyas2711

**Comment by shreyas2711** [comment]
Had a doubt should I create the api endpoints too?

**Comment by aakshitaa** [comment]
Not sure about what's the question, API endpoints for what? (Also you can ping me on discord)

**Comment by aakshitaa** [comment]
@shreyas2711 this issue has been completed by @ThapaVinay , you had done well and I really appriciate your efforts but you didn't complete the issue first. But dont worry, you can get yourself other issues assigned and work on them. All the best ✨
