### ISSUE TITLE
Create a Footer

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#3]
The footer will basically contain the contact us section and will be present in each and every page. This will be helpful for contacting the team in case of bug or issue in the web app.

**Comment by helloakash1701** [comment]
I would like to work on this

**Comment by Siddharthaaa21** [comment]
would like to work on

**Comment by aakshitaa** [comment]
sure you can @Siddharthaaa21
