### ISSUE TITLE
Custom user authentication using college mail ID (Outlook)

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#4]
Create a custom authentication on firebase using outlook.Here's a general outline of the process:

Set up your Firebase project: Start by creating a new Firebase project or using an existing one.

Set up Outlook API: You'll need to register your application with the Microsoft Developer Portal to obtain the necessary credentials and enable access to the Outlook API. This involves creating an Azure AD application and configuring the required scopes.

Implement the authentication flow: You'll need to handle the authentication flow in your application. This typically involves using the Microsoft Authentication Library (MSAL) to authenticate users with their Outlook accounts and obtain an access token.

Exchange the access token for a Firebase token: Once you have obtained an access token from the Outlook authentication flow, you'll need to exchange it for a Firebase token. This can be done using the Firebase Admin SDK or a server-side implementation.

Authenticate with Firebase: Finally, use the Firebase token to authenticate the user with Firebase Authentication. You can use the signInWithCustomToken method to authenticate the user in your client-side application.

*Note: No need to create a database for all the students logining in, basically we just have to authenticate their email id that is: <SAP ID>@stu.upes.ac.in , that's it, we don't have to store their information while logining in.

**Comment by aakshitaa** [comment]
sure

**Comment by rohin079** [comment]
I would like to work on this issue under OSOC'23

**Comment by aakshitaa** [comment]
okay @rohin079

**Comment by aakshitaa** [comment]
@helloakash1701 this issue was completed by @rohin079 . You can continue working on other issues.

**Comment by helloakash1701** [comment]
Sure 🙌
