### ISSUE TITLE
Create the home page 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#46]
Our website is lacking the home page. Create a nice Home Page that will welcome the users using our webapp. The Home page will include a warm welcome text such as - 
"Lost and Found: We'll Help You Find" 
"Lost and Found : We are here to help you" 
"Lost and Found: Reuniting Lost Treasures"
"Find What's Lost, Restore What's Found"
"Lost and Found Hub: Discover Lost Possessions"
"Lost and Found Solutions: Connect. Reclaim. Rejoice."
"Lost and Found Tracker: Rediscover Your Belongings"
"Lost and Found Central: Empowering Lost Item Recovery"
"Lost and Found Connect: Reconnecting Lost Memories"
"Lost and Found Network: Bridging the Gap of Loss"
"Lost and Found Locator: Recover What's Missing"
"Lost and Found Database: Uniting Owners and Found Items" 

Here are some inspiration:

<img width="460" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/afebd2b0-7af1-46e8-a3a3-577a3c655c1d">
<img width="588" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/7d850b0e-b8fe-4e3a-9374-6d94bb774eea">
<img width="527" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/e2c2b582-0571-4848-a600-5b8dd6ce9d07">

*Note - Don't forget to add the navbar in the page

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure Go ahead!

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
