### ISSUE TITLE
Create a FAQ Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#49]
Create a page that will contain FAQs so that our app will be more user friendly. Ping me on discord to get the google form which contains the questions which have to be added 
* Note- Don't forget to add navbar in the page
Here is some inspiration for the UI -
<img width="382" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/9cbb91df-bcfd-4c4f-bd9b-b6cb9ac89eab">
<img width="487" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/60a9f882-7de3-4ad9-9ce6-2788cce32ca3">
<img width="600" alt="image" src="https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/c69c89d1-f1c3-4a33-894b-86cdb4ba89c5">

**Comment by helloakash1701** [comment]
I would love to work on it

**Comment by aakshitaa** [comment]
Okay go ahead @helloakash1701

**Comment by ThapaVinay** [comment]
can i work on this?

**Comment by aakshitaa** [comment]
sure @ThapaVinay

**Comment by aakshitaa** [comment]
@helloakash1701 this issue was completed by @ThapaVinay , continue working on other issues!
