### ISSUE TITLE
Found Item Detail uploading page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#5]
This page will be used by the people who have found someone's item and it will be used for uploading item details which will include the following details:

•	Image (mandatory)
•	Description
•	Date
•	Place
•	Category 

Item is identifiable or not (if it is possible to know about the user via item):
	If item is identifiable- 
	Owner Name
	Any other details present
	Else- No other details necessary

**Comment by helloakash1701** [comment]
I would like to contribute in it

**Comment by aakshitaa** [comment]
sure

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure go ahead!

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
