### ISSUE TITLE
Create About Us page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#50]
Create a page which will contain details about us like why was this web app built what are it's features and what are some future scope. 
Refer to this for further context-

At our Lost and Found web app, we are dedicated to reuniting people with their lost belongings and restoring what's been found. We understand the frustration and anxiety that comes with losing something valuable, whether it's a sentimental item or a daily essential.  

Our mission is to provide a reliable platform where users can report lost items, search for their missing possessions, and connect with the individuals who have found them. We believe in fostering a community that values honesty and compassion, enabling the return of lost treasures to their rightful owners.

With our intuitive interface and powerful search features, we aim to streamline the process of recovering lost items. Our advanced matching algorithms ensure that potential matches are accurately identified, increasing the chances of successful reunions.

Our team is comprised of dedicated individuals who are passionate about facilitating the return of lost belongings. We are committed to providing exceptional support and assistance to both those who have lost something and those who have found a lost item. We believe in the power of technology to bridge the gap and bring people together, creating a positive impact on the lives of individuals and communities.

Join us in our mission to reunite lost possessions with their owners. Together, we can turn the misfortune of loss into a glimmer of hope and restore what has been lost. 

*Note- Add more context if you like :)

**Comment by helloakash1701** [comment]
I would love to work on this

**Comment by sachinaggarwal18** [comment]
I would like to work on this

**Comment by aakshitaa** [comment]
Sure @sachinaggarwal18

**Comment by shreyas2711** [comment]
Can i work on this?

**Comment by aakshitaa** [comment]
@shreyas2711 @sachinaggarwal18 this issue was completed by @helloakash1701 , continue working on other issues
