### ISSUE TITLE
Change the favicon

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#51]
Update the current favicon which is the react logo, with our webapps logo
![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/103314396/2a57cdde-0b93-430f-a18d-7dcc2f809203)

*Hint- You can find this here : lost-and-found-webapp/src/images/Logofornavbar.png

**Comment by ThapaVinay** [comment]
ok i will do it

**Comment by aakshitaa** [comment]
Sure go ahead

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
