### ISSUE TITLE
Lost Item Details uploading page 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#57]
This page will include the details of the item that is lost by the user. See the following list to note what all details have to be filled. 
**Note** :   "!" means required detail

!	Description
!	Date
!	User Ph no.
!	User Name
!	SAP ID
!	Category 
•	Name (for any other)
•	Image (optional)
•	Place

The form should be made in such a way that Name ( for any other should be visible only once the user selects any other in either of the category mentioned in the workflow.md

**Comment by ThapaVinay** [comment]
just a normal form page right? form page like the feedback form i made is okay?

**Comment by aakshitaa** [comment]
Yeah, you can refer to the canva presentation for ideas.

**Comment by ThapaVinay** [comment]
ok i want to work on this

**Comment by aakshitaa** [comment]
@ThapaVinay okay sure!

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
