### ISSUE TITLE
Create a collection in MongoDB named Found Items DB

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#6]
In this collection we will store the complete information of all the items entered by users. Once the correct owner of the item is found the item will be moved from this collection to Collected Items DB
*Note: This collection will not contain the items that are reported to be lost. They will be stored in another collection.
*It is mandatory for user's reporting found items to uplaod image of the found item hence this will contain image for each item.

**Comment by tarunvenkat** [comment]
Hey @aakshitaa I want to work on this issue

**Comment by aakshitaa** [comment]
okay sure @tarunvenkat

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
Yes sure @rohin079

**Comment by aakshitaa** [comment]
@tarunvenkat this issue was completed by @rohin079. You may continue working on other issues. Happy Contributing!
