### ISSUE TITLE
Navbar Fix 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#60]
Fix the navigation in the navbar and add feedback button instead of contact us section

**Comment by helloakash1701** [comment]
I would love to work on it

**Comment by aakshitaa** [comment]
Sure get on it @helloakash1701

**Comment by ThapaVinay** [comment]
let me fix it

**Comment by aakshitaa** [comment]
Okay sure @ThapaVinay

**Comment by aakshitaa** [comment]
@helloakash1701 this issue was completed by @ThapaVinay , please find another issue to work on
