### ISSUE TITLE
The current favicon and its content are not visible

### ISSUE THREAD

**Issue by helloakash1701** [upes-open/OSoC-Lost-And-Found-WebApp#64]
Try this favicon instead, 

![image](https://github.com/upes-open/OSoC-Lost-And-Found-WebApp/assets/80618499/256150c6-0133-4cf4-b099-a516235583a6)

It is simple and displays its content

**Comment by aakshitaa** [comment]
Okay sure, I'll assign you

**Comment by helloakash1701** [comment]
Thankyou :)

**Comment by aakshitaa** [comment]
This issue was completed by @helloakash1701
