### ISSUE TITLE
Integrate the Lost Items Detail Page with the Backend

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#68]
The lost item details page is availble but not functional. Integrate it with the backend and store the details enterred by the user into our already build schema. To get the credentials for backend contact me.

**Comment by rohin079** [comment]
I would like to work on this issue under OSoc'23

**Comment by aakshitaa** [comment]
Sure @rohin079

**Comment by aakshitaa** [comment]
This issue was completed by @rohin079
