### ISSUE TITLE
Integrate Found Items Details Page with the Backend

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#69]
The found items details uploading page is made and committed. Integrate it with the backend already created in MongoDB. Text me to get credentials for the shared cluster.

**Comment by rohin079** [comment]
I would like to work on this issue under OSoc'23

**Comment by aakshitaa** [comment]
Sure rohin Go ahead!

**Comment by aakshitaa** [comment]
This issue was completed by @rohin079
