### ISSUE TITLE
Create a collection in MongoDB named Collected Items DB 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#7]
This collection will contain the information about the items that are claimed by the user. It will store the following information-
Item details: The item details will be moved from the Found Items DB to this Collection. 
*Note: Moved means it has to be deleted from Found Items DB
Owner details: The details of the owner/person who claims to own the item will be stored. This data will be fetched from the user details page

**Comment by avnigoyal25** [comment]
Hey i want to work on this issue.

**Comment by aakshitaa** [comment]
Sure @avnigoyal25

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
Sure @rohin079

**Comment by avnigoyal25** [comment]
@aakshitaa rohin and I will work together for this issue or separately?

**Comment by aakshitaa** [comment]
> @aakshitaa rohin and I will work together for this issue or separately?

Hey @avnigoyal25 , 1 issue can have multiple assignee (as in this case there is Rohin and you, but who so ever will complete the issue (when I approve your PR) he/she will be given the points. You have to work individually on the issues. 
Hope that solves your query. All the best!

**Comment by aakshitaa** [comment]
@avnigoyal25 this issue was completed by @rohin079. You may continue working on other issues. Happy Contributing!
