### ISSUE TITLE
Create a page to view details of items of the items gallery

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#75]
Once the user clicks on the see details button of an item in the items gallery page, then they will be directed to this page and they can view all the item details including detailed description.

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure @ThapaVinay  !

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
