### ISSUE TITLE
Create a collection in MongoDB named Lost Items DB 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#8]
This collection will contain the details of items that are reported to be lost by the user. This will include 
Item details: including category, description, identifiable characteristics
date and place where lost
image of item (if possible)

**Comment by helloakash1701** [comment]
I would like to work on this

**Comment by aakshitaa** [comment]
sure

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
Okay go ahead

**Comment by aakshitaa** [comment]
@helloakash1701 this issue was completed by @rohin079. You may continue working on other issues. Happy Contributing!

**Comment by helloakash1701** [comment]
Sure
