### ISSUE TITLE
Integrate the Login Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#80]
The login page needs to be integrated with the backend and it should not include the navbar, just the basic page with the login button. When the user clicks on the login button, they have to be directed to the outlook authentication page. 

!Note- No user should be directed to anyother page without logging in. Also have a logout button in the navbar so that user may logout. User will only be logged out once they click on the logout button!

Use session handling for this and don't logout the user on it's own after they close the tab, the session has to end only once the user clicks on the logout button

**Comment by rohin079** [comment]
i would like to work on this issue under OSoc'23

**Comment by aakshitaa** [comment]
Okay sure @rohin079

**Comment by aakshitaa** [comment]
This issue was completed by @rohin079
