### ISSUE TITLE
Integrate the Items Gallery Page with the Backend

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#84]
The backend and frontend for the items gallery page is ready. Integrate them such that when the user selects the category then a query is run that filters out the items based on that particular category. The item details are fetched from the found-items db.

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure go ahead @ThapaVinay

**Comment by aakshitaa** [comment]
@rohin079 this issue was completed by @ThapaVinay , continue working on other issues
