### ISSUE TITLE
Integrate the Help Us Find Page with the Lost Items DB

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#88]
The help us find page will fetch the data from thw lost items db and display it. Select the default image "image not found" for the items whose image is not available.

**Comment by jason2000-cpu** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
sure @jason2000-cpu

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
sure @ThapaVinay

**Comment by aakshitaa** [comment]
@jason2000-cpu This issue was completed by @ThapaVinay , I had reviewed your PR and your code was not fetching images from the Database, it was showing the default image "image not found" for all the items. I had asked you about this on discord as well.
Please find another issue to work on!
