### ISSUE TITLE
Integrate the claiming procedure

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#89]
Once the user clicks on the "Claim item" button in the items galler, redirect the user to the user details uploading page (already made).
Once the user fills in all the required details correctly, then DELETE that item info from the lost items db and store it in the collected items db.

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
Sure @rohin079

**Comment by aakshitaa** [comment]
This issue was completed by @rohin079
