### ISSUE TITLE
Item Gallery Page- Category Selection 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#9]
On opening the items gallery page there will be a list of category available (see ReadME.md for category details) and from there they will select the category  they are looking for. So you have to create the Category Selection Page

**Comment by helloakash1701** [comment]
I would like to work on this

**Comment by aakshitaa** [comment]
sure

**Comment by Roh1tHooda** [comment]
I would like to work on this too please.

**Comment by aakshitaa** [comment]
Okay @Roh1tHooda all the best

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure go ahead @ThapaVinay

**Comment by aakshitaa** [comment]
@helloakash1701 @Roh1tHooda this issue was completed by @ThapaVinay , kindly find another issue to work on!
