### ISSUE TITLE
Work on the dark mode of each page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#95]
Currently the pages are made but they are not looking good in the dark mode, work on that. Add different background images in the dark mode.

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
Sure @ThapaVinay

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
