### ISSUE TITLE
Populate the Database

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/OSoC-Lost-And-Found-WebApp#98]
Populate the database by adding sample data to it. Make sure you:

- [ ] Use relevant names and not gibberish
- [ ] add some images in the Lost Items db but not for every item
- [ ] remove the existing data

** You have to populate all the collections- feedbacks, founditems, collecteditems, lostitems
** Each collection must have atleast 20 entries

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by aakshitaa** [comment]
sure @rohin079

**Comment by aakshitaa** [comment]
This issue was completed by @rohin079
